---
abstract: 'Yet another SQL Generator'
author:
  - 'Sugama Keita <sugama@jamadam.com>'
build_requires:
  Test::Class: 0.36
  Test::More: 0.47
  Test::UseAllModules: 0.10
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-OOP
no_index:
  directory:
    - t
    - inc
requires: {}
resources: {}
version: 0.21
